export const product_list = [
    {
        id:1,
        pname:"SAVSEA soft charcoal toothbrush",
        image:"https://m.media-amazon.com/images/I/81yCCF-xyaS._SL1500_.jpg",
        category:"toothbrush",
        rating: 4,
        link:"https://www.amazon.in/SavSea-Soft-Charcoal-bamboo-toothbrush/dp/B08RXHC79K/ref=sr_1_5?keywords=sustainable%2Bproducts&qid=1689952914&sr=8-5&th=1",
    },
    {
        id:2,
        pname:"NECAVU vegetable bag",
        image:"https://m.media-amazon.com/images/I/A1w9MSOxlfL._SL1500_.jpg",
        category:"bag",
        rating:3,
        link:"https://www.amazon.in/Eco-friendly-natural-vegetables-vegetable-Multi-purpose/dp/B09N2MTK8Y/ref=sr_1_6?keywords=sustainable+products&qid=1689952914&sr=8-6",
    },
    {
        id:3,
        pname:"rescript ecofriendly pencil",
        image:"https://m.media-amazon.com/images/I/41-I2rfhRdL._SL1080_.jpg",
        category:"pencil",
        rating: 4,
        link:"https://www.amazon.in/rescript-Eco-Friendly-Recycled-Sustainable-Stationery/dp/B0BY58JMBM/ref=sr_1_7?keywords=sustainable+products&qid=1689952914&sr=8-7",
    },
    {
        id:4,
        pname:"Niyori vegetable bag ",
        image:"https://m.media-amazon.com/images/I/61C52eFjrZL._SL1500_.jpg",
        category:"bag",
        rating: 4,
        link:"https://www.amazon.in/Niyori-Reusable-Vegetables-Multipurpose-Friendly/dp/B0C2KDQK3H/ref=sr_1_11?keywords=sustainable+products&qid=1689952914&sr=8-11",
    },
    {
        id:5,
        pname:"Indegenious living loofah",
        image:"https://m.media-amazon.com/images/I/81Zj+fudMCL._SL1500_.jpg",
        category:" loofah",
        rating: 4.5,
        link:"https://www.amazon.in/Premium-Natural-Eco-Friendly-Shower-Loofah/dp/B09B2BG3P2/ref=sr_1_13?keywords=sustainable+products&qid=1689952914&sr=8-13",
    },
    {
        id:6,
        pname: "Beco bamboo toothbrush",
        image:"https://m.media-amazon.com/images/I/51zkBsfeH-L._SL1000_.jpg",
        category:"toothbrush",
        rating:4.5,
        link:"https://www.amazon.in/Bamboo-Toothbrush-Charcoal-Activated-Bristles/dp/B08GSSJ1FG/ref=sr_1_14?keywords=sustainable+products&qid=1689952914&sr=8-14",
    },
    {
        id:7,
        pname:"mCaffeine exfolating gloves",
        image:"https://m.media-amazon.com/images/I/61S10ajA0mL._SL1100_.jpg",
        category:" loofah",
        rating:4,
        link:"https://www.amazon.in/mCaffeine-Exfoliating-Cleansing-Scrubbing-Sustainable/dp/B09H7QF6RR/ref=sr_1_15?keywords=sustainable+products&qid=1689952914&sr=8-15",
    },
    {
        id:8,
        pname:"Happi planet dishwash liquid",
        image:"https://m.media-amazon.com/images/I/61YYsFpbxoL._SL1500_.jpg",
        category:"cleaning",
        rating:4.8,
        link:"https://www.amazon.in/Happi-Planet-Eco-Friendly-Dishwash-Biodegradable/dp/B0B4GBRQR8/ref=sr_1_16?keywords=sustainable+products&qid=1689952914&sr=8-16",
    },
    {
        id:9,
        pname:"Happi laundry detergent",
        image:"https://m.media-amazon.com/images/I/61vvArV2SkL._SL1500_.jpg",
        category:"cleaning",
        rating:3,
        link:"https://www.amazon.in/Happi-Planet-Eco-Friendly-Detergent-Biodegradable/dp/B0B42X9MC9/ref=sr_1_25?keywords=sustainable+products&qid=1689952914&sr=8-25",
    },
    {
        id:10,
        pname:"Happi fabric softner",
        image:"https://m.media-amazon.com/images/I/61MR2N207PL._SL1500_.jpg",
        category:"cleaning",
        rating:4.2,
        link:"https://www.amazon.in/Happi-Planet-Eco-Friendly-Conditioner-Biodegradable/dp/B0B4342DS7/ref=sr_1_26?keywords=sustainable+products&qid=1689952914&sr=8-26",
    },

]